# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Zinit: https://github.com/zdharma/zinit
ZINIT_HOME="$HOME/.zinit"
ZINIT_BIN_HOME="$ZINIT_HOME/bin"
ZINIT="$ZINIT_BIN_HOME/zinit.zsh"

# Install zinit.zsh if not exist
if [ ! -f "$ZINIT" ]; then
	echo "Installing zinit ..."
	[ ! -d "$ZINIT_HOME" ] && mkdir -p "$ZINIT_HOME" 2> /dev/null
	[ ! -d "$ZINIT_BIN_HOME" ] && mkdir -p "$ZINIT_BIN_HOME" 2> /dev/null
	URL="https://github.com/zdharma-continuum/zinit.git"
	if [ -x "$(which git)" ]; then
		git clone "$URL" "$ZINIT_BIN_HOME"
	else
		echo "ERROR: please install git before installation !!"
		exit
	fi
fi

# Initialize antigen
source "$ZINIT"

# 
zinit ice lucid wait='0' atinit='zpcompinit'
zinit light zdharma-continuum/fast-syntax-highlighting

zinit ice lucid wait='0' atload='_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

zinit ice depth=1

MY_OMZ="https://gitee.com/mirrors/ohmyzsh/raw/master"
MY_OMZL=${MY_OMZ}/lib
MY_OMZP=${MY_OMZ}/plugins
zinit snippet ${MY_OMZL}/history.zsh
zinit snippet ${MY_OMZL}/completion.zsh
zinit snippet ${MY_OMZL}/git.zsh
zinit snippet ${MY_OMZL}/key-bindings.zsh
zinit snippet ${MY_OMZL}/theme-and-appearance.zsh
zinit snippet ${MY_OMZP}/pip/pip.plugin.zsh
zinit snippet ${MY_OMZP}/colored-man-pages/colored-man-pages.plugin.zsh
zinit snippet ${MY_OMZP}/sudo/sudo.plugin.zsh

zinit light romkatv/powerlevel10k

# system path setting
if [[ "$OSTYPE" =~ ^darwin ]]; then
        export PATH=/opt/homebrew/bin:$PATH

elif [[ "$OSTYPE" =~ ^linux ]]; then
	[ -z "$TMUX" ] && TERM=xterm-256color

	# >>> conda initialize >>>
	# !! Contents within this block are managed by 'conda init' !!
	__conda_setup="$('$HOME/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
	else
		if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
			. "$HOME/miniconda3/etc/profile.d/conda.sh"
		else
			export PATH="$HOME/miniconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup
	# <<< conda initialize <<<
fi

# alias
[ -f ~/dotfiles/zsh/alias.zsh ] && source ~/dotfiles/zsh/alias.zsh
[ -f ~/dotfiles/zsh/custom.zsh ] && source ~/dotfiles/zsh/custom.zsh

# To customize prompt, run `p10k configure` or edit ~/dotfiles/zsh/p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
